process faults {6: ({6, 4}, 3988666334)}
network faults {3: [{0}, {1}, {4, 5, 2}, {3}, {6}]}
{8: ("B3FE66226EBCC2281623437877838427789681328170969628CD66B5832D7C17", {0, 5, 1, 3, 6, 2, 4}), 6: ("D72EC87ABDB425D70C8889627915791A3A238752E4E9E47E8E631E4A30A59B94", {6, 2, 5, 1, 3, 0, 4}), 7: ("3F0DBECE0FF7A04229DE6221026C8F091098B54F88538E04F788B73A9C4BDB85", {1, 4, 5, 0, 6, 2, 3}), 9: ("361FD754739843D4DBDC213147E512AE02AE7F71459EE3DA6A7D90F9C43C98AF", {3, 0, 5, 2, 4, 1, 6}), 5: ("70E6BA20F1CEC59EAC3188CDD661BE917BB38C0CE108959442E0519EABC199DB", {4, 2, 6, 1, 0, 3, 5}), 10: ("D0ABB28CE3DFDAC17905C7012ED393C6B6A857B3B5FAA966380D9E0123A25D8D", {6, 0, 2, 1, 3, 5, 4})}
7
reason: all committed
done!
