process faults {3: ({4}, 2643611791)}
network faults {4: [{0}, {4, 1, 5, 6}, {3, 2}], 6: [{4, 5, 0}, {6, 1, 3}, {2}]}
{6: ("A76A315142FE6CBFB42F014AA70378896340D5572A16E35C3567F450DCD16639", {5, 1, 0, 4, 6, 3, 2}), 10: ("7AE10BF3E28CD34BE36228DD9AF6B044B180B7D04871BA57A226DD41CF247BA0", {5, 4, 1, 2, 3, 6, 0}), 7: ("85543BBF45A398CA09A15C4CD581AD564E43821AD68E0B4041FABF32FB0FF2E5", {1, 4, 5, 6, 2, 0, 3}), 8: ("5D57AAEC1184E8EA1B15EDCBF0526FEEA11015149C2CF33D1359C52B367980AA", {4, 5, 6, 3, 0, 1, 2}), 9: ("6EA066D7E112C8A260D0DDF3C04169D19FD212BEB40943A94C8BB16B7B329878", {5, 2, 0, 4, 6, 3, 1}), 5: ("F81F62C575AF856FE0E225DB64937A3F550C6A18D5922C457C1EF3F7CD91D4C8", {1, 0, 2, 4, 3, 5, 6})}
7
reason: all committed
done!
