process faults {6: ({4, 2}, 378968269)}
network faults {5: [{5, 4, 0}, {3, 1}, {2, 6}]}
{10: ("58134963DE88C88F43DED0D4371B0F913E97CBEA2EC38DB127717E245F91E199", {2, 4, 1, 6, 5, 3, 0}), 6: ("83623D180FC604BA49ADDA281848DEB5371F5094166AAA149829A0D7BA848C08", {4, 1, 0, 6, 3, 5, 2}), 7: ("CE176F01991C3A27FE2A52E93B7CF76864B4AEDDB1F10C06F28B45810D696B39", {3, 2, 4, 5, 1, 6, 0}), 5: ("874D5D4A987F9BBE2FB4EAF60940B0AF1FB51E5F9693DE10E77A312D0EA62874", {1, 3, 4, 0, 5, 6, 2}), 8: ("C16D07369A9DEE73A8FB8F27616768BEA51D4740B44E5F6CE0491BF5707813E8", {0, 1, 4, 5, 3, 6, 2}), 9: ("BFCF7F6D4888559CD153A858BB0C33D7B845E337EACBD61FA2B8D48C41E3AF1C", {4, 1, 0, 2, 5, 3, 6})}
7
reason: all committed
done!
