process faults {6: ({0, 1}, 2327489671)}
network faults {4: [{0}, {3, 1, 6}, {2, 4}, {5}]}
{10: ("E44A2286958D6DCCF20AFDFB972D86091D9EC867EF688D7B67498E8908441BD7", {4, 5, 2, 6, 1, 0, 3}), 5: ("E7956F17F9FF99ACDF087891FACF0ADFAC6040A2A22C96290CE376B48A7526ED", {6, 0, 4, 3, 5, 1, 2}), 7: ("97D8D75ACB4548A4C0AF10843A56554D2A298035972A7F2313ED5E1616B79968", {5, 1, 2, 4, 3, 6, 0}), 9: ("02583D195930DAE936FC4B4014252BF9EDBF433F775EE095827CBF2307981EA2", {3, 0, 4, 6, 5, 1, 2}), 6: ("A9FA81DF8D47607653F862A025572F90B873236D87CF571C36A141451272B132", {1, 4, 6, 0, 5, 3, 2}), 8: ("6584DD615FF367FA3B429D1E1B99038FB0D0C5BEE9F9E0FBFFB0FDFEE38945B3", {4, 6, 2, 1, 3, 0, 5})}
7
reason: all committed
done!
