process faults {6: ({2, 0}, 3067178395)}
network faults {4: [{0, 6, 4}, {1, 2}, {3, 5}]}
{5: ("8069EA0DDBB62021AC21ED3694ABAD8BE1BCEA56F5D1FAA53B6E4C3C7BC3597E", {4, 1, 2, 0, 5, 3, 6}), 7: ("14990B337C69D4ABC8BF4B899F8552231909A01CF69447C9804B366728F0A43B", {1, 5, 6, 3, 0, 4, 2}), 8: ("EE2BFD9181A987D3FF34916EF31CCA2D72B245DD7E0F53EBE79366314E80B19E", {5, 4, 0, 6, 2, 1, 3}), 6: ("6AE868ADE793C3809316E0CB4AA49EB6EFA5730C19A53E5E5429764249EE7FF2", {2, 5, 4, 6, 0, 3, 1}), 9: ("59A4A0D0D925CE7578C006B189EF9F88F4B7E6527C3456792740072ACAE70530", {5, 1, 2, 6, 3, 4, 0}), 10: ("3FB5B942650EE732334003D0A5E6B6C357E64D2DAE80B4E988F21CA971E3A949", {5, 3, 4, 2, 6, 1, 0})}
7
reason: all committed
done!
