process faults {3: ({0, 2}, 958507038)}
network faults {6: [{0, 1, 3, 6}, {2, 5}, {4}]}
{9: ("EC2235C62B2805FB7470165FE449F33DC659EF6928F0B5281D9EF0DBAB18EF82", {4, 5, 1, 2, 0, 6, 3}), 10: ("0E7D62FC817D397080702D20F146C111539183F21BEAF1E1B5A12F123B5901E6", {0, 3, 4, 2, 1, 5, 6}), 8: ("0F7D7C205006E4DD0D093C121F1C13F29BE920BC9556F49393CEB163497AED87", {5, 1, 3, 4, 0, 2, 6}), 5: ("5EC58FDA76B65865F4882FE49BDEA4ADB720D4B7270541B58B41A85A957B646C", {5, 4, 2, 1, 6, 0, 3}), 6: ("41F6DDBEE6E7FD97B55E3F6575E8F667BDB8B300889F7B78C18073FC42C6CA7C", {5, 1, 0, 6, 3, 4, 2}), 7: ("5784D287FB4C104BC06C807FB19F6738B820D4B36BE24DA8959B78AB4E487599", {2, 6, 1, 0, 3, 5, 4})}
7
reason: all committed
done!
