process faults {7: ({5}, 996108327)}
network faults {2: [{2, 0}, {6, 1, 3, 4}, {5}]}
{5: ("EF78E209F81E237A8E4F67C7E9F524E44FBD3A8CFEFD813730266F725630A051", {3, 2, 5, 6, 1, 0, 4}), 6: ("29A7A0E6D7331C4E61E2BA2C7344A662BA86B000D4564BA9FA72BD63DCE675F9", {1, 6, 0, 5, 4, 2, 3}), 9: ("556BA161BAFDAD6F222FD5EA99323FF69B7D6245419E7136C441BB463CC0A0CD", {4, 3, 1, 5, 0, 6, 2}), 10: ("24469BC4CF8DCF9FA3B685F84EC03F0FED2FD71684DFB8C10AF3BC2C7F6CFD96", {3, 1, 6, 4, 0, 2, 5}), 7: ("1228021E5A45D8F28B39F2B96571FC7EB20962EDA3CE7F18C807F8E26083A7C8", {2, 0, 4, 1, 6, 3, 5}), 8: ("6336E5CBC8A6011642A590604B670D2F15637B00810EBAEB2055852C82C903F5", {0, 3, 2, 4, 6, 1, 5})}
7
reason: all committed
done!
