process faults {7: ({2}, 1923514020)}
network faults {7: [{6, 0, 5}, {2, 1}, {3}, {4}]}
{7: ("211CF620E2337957ED0FF5643FEAA0C98CF96D2DE85AFD67C087B656DB8748F0", {5, 4, 0, 3, 1, 2, 6}), 9: ("9BC9ED9AE93FB70E26B0637A9681A091BDAA5542E512BD416333F7C0932422AC", {4, 2, 6, 3, 0, 1, 5}), 5: ("FB23DBF92BD746FF0F436424B4A0EE1AAE223AC5CF9E46C1E12E55AA947FE3DC", {1, 4, 5, 2, 0, 6, 3}), 6: ("D5CB0F44891C8041685011E7AAB77D25514EA38B287001BB5D70C82E311A0066", {4, 5, 3, 0, 2, 6, 1}), 10: ("F2DD4A65CA951D346A0510CBEA57F9FF074BF1DA0E8F3BE05B8B21939DB80484", {4, 1, 0, 2, 5, 3, 6}), 8: ("F35FA5084CA0A9C260E29E0134D877FF28BC760B2A2CEDD524D3BA2CCC896D06", {4, 0, 5, 2, 6, 1, 3})}
7
reason: all committed
done!
