process faults {7: ({2, 4, 6}, 2397616477)}
network faults {6: [{0}, {1, 4}, {5, 2}, {3, 6}]}
{9: ("F61BC220528E9B664BD4E2FAB65ECC3FE03C8941962E4436EA2BE98A58361980", {5, 4, 1, 0, 3, 2, 6}), 10: ("6F59AC108546A3C741C5785DE8F855914A404D9FB26D6C21C54EF73459DCECD7", {5, 3, 2, 6, 4, 1, 0}), 6: ("1630A9CEFD23E4CFE2650B3B6576C90E2137B06ECF1B218D1E9455B2B37A465B", {5, 2, 6, 1, 3, 4, 0}), 7: ("8BE9ED64298A861A9EF3C55F7C3A9AEC8C5ECA4B7D1692E766A13843C0ED6DE5", {3, 4, 6, 5, 0, 1, 2}), 8: ("9502E15EB399E353BF3BFBB5127D567682ED40908D85E2527361ED41115D7278", {6, 4, 1, 5, 3, 0, 2})}
7
reason: all committed
done!
