process faults {4: ({1, 4, 2}, 10903976)}
network faults {2: [{0, 4, 1, 3, 2}, {5}, {6}]}
{5: ("6DCEB0AC93C4FC8CBDE49A4035834F5392772F8EC71BBCAB4DD817B41BC28262", {0, 2, 6, 3, 1, 5, 4}), 7: ("31C0AEBA65D80C87F6DB28194C86B022077DE903F7424C4D747C6D07D3DFD435", {3, 4, 5, 6, 1, 0, 2}), 9: ("BCB2277785C4492249FD5F204E48CB55CB262DDC1E3FB824850870CDA1626B05", {5, 4, 1, 6, 0, 3, 2}), 10: ("1CC0782465A4951CA87C301469205F0C4E1AD172DB878807C6934FD773D117D7", {0, 3, 6, 5, 4, 2, 1}), 8: ("E2809A62ABD0015575B4EF44ADFA95093DCEE96ECE9BCC952C52E91DE51FB5FE", {1, 4, 0, 2, 5, 6, 3}), 6: ("77DF8BB3A6156AB1ED7A6941A0C4E0B4BB1C2D9A9FF2E8510B7902AB568BD76D", {1, 4, 5, 6, 3, 2, 0})}
7
reason: all committed
done!
