process faults {7: ({2, 4, 1}, 1625989928)}
network faults {}
{9: ("DE6DFFEDE77A860068CE0F93DE9D1594B5FB9DDED2E549BD1A9DBD267F561BC9", {5, 6, 0, 3, 1, 2, 4}), 10: ("54859D353B754A3929E4BB1525A13575F02C52DF63591AF58493F54B171221D9", {5, 1, 2, 4, 6, 0, 3}), 6: ("4BA70821A6FECE0DC254887AD608D904551D4890BCFF879EC658D8AC1AD84E65", {3, 1, 4, 6, 0, 2, 5}), 8: ("87D87A13D1CF36CCA7B52BBDE2052BAEE37A2F2E3A7534E43FEDE76B9789E7D0", {4, 3, 5, 1, 0, 6, 2}), 5: ("00B601E2C2A0F374A1B269F3C9AB6B66B3F7262C512B368ED1B9A62077A46DD3", {4, 3, 1, 0, 5, 6, 2}), 7: ("DF2F54A017EBDA8ACA98EEDB00085BC6D70465D6BDD7C0FF40B49E6BEFBB8444", {6, 5, 2, 3, 0, 1, 4})}
7
reason: all committed
done!
