process faults {6: ({0, 1, 2}, 1994386808)}
network faults {}
{8: ("9BE75566292282185A515CE10D4D660C76679826A015BEACE892799E5B4EE4AA", {0, 2, 1, 4, 6, 3, 5}), 10: ("EC0AF1B3B287049D7724C73697EEF26897309DCAA67143BA9B070EEAE2F22AA0", {6, 3, 0, 5, 4, 1, 2}), 6: ("B94EA4BF473EA7E4252D2559A35115244E6287ABCA7BCDEF1DC1296ABFE77EEC", {2, 3, 4, 1, 0, 6, 5}), 9: ("927DFEED8B8A604824BAEB2C30C145583E93868590D4EBD864B23F99F8DCF280", {0, 2, 4, 5, 1, 6, 3}), 7: ("1E468E7F43DFD3A1921487B944239EC38E4851251A59C54816FE3C430EFC22DB", {0, 2, 4, 5, 1, 3, 6})}
7
reason: all committed
done!
