process faults {7: ({5, 2, 6}, 563041946)}
network faults {3: [{6, 0, 2}, {4, 3, 1}, {5}]}
{9: ("05FCB500848104C3161A1DE82745DA023F4503CB7A2443909DB86627079C363B", {2, 0, 5, 3, 6, 1, 4}), 6: ("EF1DF5191682D46098FD48DC2C3CA3960B0E70FB462CD8D3CC028A598296F5C2", {5, 1, 3, 4, 0, 2, 6}), 7: ("F0943FFB09718DF818D8BECBB1EA73BEFFD5E4FE4CA2CF0442E61590B2F01CCB", {4, 1, 0, 6, 2, 3, 5}), 8: ("4E0A08C811FB4C06827D97496C8F7B6B9776F40C117919BB830E2D19F649BE6A", {4, 2, 6, 3, 0, 1, 5}), 10: ("9B257177ECA5F6EC5DD9AF454B37DA98EF5748083335BD92E6744C47FBAA866F", {2, 3, 0, 5, 1, 4, 6}), 5: ("18B2AC3704A0163488BA0C71F44229A6BE5BC508C7F00F03FBF5F8795CE6896F", {6, 5, 2, 1, 4, 0, 3})}
7
reason: all committed
done!
