process faults {6: ({1, 4}, 3497514410)}
network faults {6: [{1, 3, 6, 0}, {2}, {4, 5}]}
{6: ("542A5F4925030DAC115A6A729ED953800F7A2903FA2E2F0E2DAACE9CF91EF408", {6, 2, 5, 1, 3, 0, 4}), 7: ("B010924C9A5E5009E5B470D4A78DFAD1CB1B577D09D73C04B1E5F06E9EBFCFDF", {1, 4, 5, 6, 3, 2, 0}), 8: ("0B38EB3C555CBE8D457A776570FE8579AE122C10E3BAF5AF12CEDAE7FA657C6F", {5, 4, 1, 3, 2, 6, 0}), 10: ("3D45D34C8ECE0EF9D5328A1C9B50B1F090AEC4C8630A841EE3BB0D3CA93BAEBB", {6, 3, 2, 0, 4, 5, 1}), 5: ("E0AB0F17F75B69D854762F73B56F2A6BDC81944CD2694253B9B1C08BDBAF386A", {2, 1, 0, 3, 5, 4, 6}), 9: ("E23D23E69BFC393B6616A577B832CC2C7BA576DE1AF184577925AC2F6E58FDB5", {1, 2, 3, 4, 0, 5, 6})}
7
reason: all committed
done!
