process faults {7: ({4, 5, 2}, 4128448819), 6: ({0, 2, 4}, 2208044658)}
network faults {}
{8: ("FB4763E698DD3AB800BCF1FFF080826F66E5EDFCD4CE1F5A7819756457126C36", {1, 2, 3, 4, 0, 6, 5}), 9: ("3E79CC4116C3D0E35CE0413B6C14573BDFB4E75C63D0F62846447C723054A11C", {1, 6, 5, 3, 4, 2, 0}), 10: ("11DD67AC45F2DFAEC020A4AF1D712FF09CECEDC14CB7918DCCB7A47CFD2CF8A6", {5, 6, 1, 0, 2, 3, 4}), 7: ("E6F36167861FB36668C71875DF669B32800F2210BF05CC9C6E3DB146F596A26C", {4, 3, 0, 2, 5, 6, 1}), 5: ("3DFD5302CF7B25CFDF07579FAB131D9A13B2B3718A62FDAD22283599F6D263A1", {6, 2, 5, 4, 1, 3, 0}), 6: ("3A82CF7F4391364F171F344146B685B249223B75D4EAED314C03090969ECAAF1", {4, 3, 1, 5, 6, 2, 0})}
7
reason: all committed
done!
