process faults {3: ({1, 0}, 63391174)}
network faults {6: [{0, 1, 5, 3}, {6, 2, 4}]}
{10: ("BD53AEF7BEADE291196C0D7E20E995EAB7E08B207D9EC07A8C8546F0BF3C4F76", {4, 1, 2, 0, 5, 6, 3}), 6: ("7CF40BEF572DDDF549C3E0F2E89863C0F1F58E6AD5E69C4C5778D3AEF977A901", {3, 5, 1, 0, 4, 2, 6}), 7: ("4995A01CAD347324FDEC73853CBB50088C4421A4BBB8F9C778B3801C7EC1AA5C", {2, 4, 6, 0, 5, 3, 1}), 8: ("9F6C9555E4C6B665BF7E5F97A0B3DE61A0D3AB4B4A70812BC0C9B6CE32CCBC5D", {2, 4, 1, 5, 6, 3, 0}), 5: ("C325BDFC60F2AAEB8FA5411EEA3EB66497BED583F43957E83507973AAB2C5DCD", {4, 0, 6, 5, 3, 1, 2}), 9: ("CF5DAD2B139F807489E160A4DDA8CBC113CB6EBC190360BDFF4CD0C4FC1FB900", {4, 0, 3, 2, 6, 1, 5})}
7
reason: all committed
done!
