process faults {6: ({4, 2}, 3502870737)}
network faults {}
{9: ("129EE5660E1AE2C7A456CBEEC024455B079705E33C54ECAE6BF30071824AD67D", {5, 1, 2, 4, 6, 3, 0}), 10: ("F058BB1CBB832FC4C6D401A97FD9285B0F060B236F026BB66B2384BA16AB954E", {5, 6, 4, 3, 1, 2, 0}), 5: ("FFB31AD64B74DBF0CABE5B43AA7A492609788BAC32CBF488E73E4CF3DDDD7F40", {4, 3, 0, 5, 2, 6, 1}), 6: ("59028EBF80CFD25D4200A0FC62FCD763F8F493F7A23D820BB1F05257ED49A3FD", {4, 2, 5, 1, 3, 0, 6}), 7: ("E7DF5DA077ADF3A2479FD48AC1555771F494D91C8913583905B88F350B0A7E05", {2, 4, 5, 1, 6, 3, 0}), 8: ("1936B077F727C0B6A18A18A6EE4ADE92371185E96A955936DB01896678A70CE0", {3, 2, 1, 0, 4, 5, 6})}
7
reason: all committed
done!
