process faults {4: ({6, 2, 5}, 2558936316)}
network faults {}
{6: ("FD3E992251FB5642DBF869DAE6B72E9BCCBC8772D49C12964A21E1F9EC34C549", {3, 1, 4, 0, 5, 6, 2}), 5: ("D2F11325154FAE747B50D6FCCF0179CF2B9DF0A72BA5D85FF9F68352B3448CAD", {3, 1, 5, 6, 2, 4, 0}), 8: ("9326AE166A37DB17741BAD6AD80ED144F9C4615EDBED3588376E36569F032A32", {2, 5, 4, 3, 6, 1, 0}), 9: ("05392A79D347D934679E4C39362FE44E9DCB9098ACDC23BA796EDE620BD8510B", {2, 0, 1, 6, 4, 3, 5}), 7: ("269D0498C609614D32EBEC68CE104C999BF83B426CC249BF3384D1AB3E71F3C2", {5, 3, 0, 2, 1, 4, 6}), 10: ("4D574BB9AACB5E1CB58C9F083F90F5B15C4CAD6A418156A653405AB81F22E140", {4, 3, 1, 2, 0, 6, 5})}
7
reason: all committed
done!
