process faults {4: ({0}, 1425746076)}
network faults {4: [{0}, {1}, {5, 2}, {4, 3}, {6}]}
{10: ("57DAC20EBB2C81305E20E88FDEC3706355A3D0E5AFFBC470926B1DFEEB3DEFCF", {1, 0, 5, 3, 4, 6, 2}), 5: ("BC207400CD014E948E326A5331CB31864ED9BCD712221EF30DFA46EF12294EF6", {5, 0, 3, 1, 6, 4, 2}), 9: ("6FA412980B8CE0D75AF24BA3645ABFC9896622A4FDDFAB7E3DF94A6E648A7399", {0, 4, 1, 2, 5, 6, 3}), 8: ("38D58DE1DE195A10299EF6CB1ABAAEF1DF01BF5C8DBA4DA4F9881FC2081EDDCF", {4, 2, 6, 3, 0, 5, 1}), 7: ("812384D62A1A681EE4C649035ABAB7C683F3CC142F64FA2C0B7A6274A9FCDAC4", {3, 0, 5, 2, 4, 6, 1}), 6: ("603DF2665F4D5CCACAC59281DD548E25318487597FFB5D3E4DFEB2331BBC3979", {4, 6, 1, 2, 0, 3, 5})}
7
reason: all committed
done!
