process faults {2: ({4, 2}, 936928276)}
network faults {}
{8: ("F328896F72496E0B68ACEA67171A2F2C72F8A935D105D4FB7B737C5DFB800D18", {0, 4, 2, 1, 3, 5, 6}), 7: ("B64342DA7339BAD9E2CFE30CA6AFC5A13358A8BB8E51AABE97CCB4B6723A7A46", {1, 6, 0, 4, 5, 2, 3}), 9: ("B3A79E345D56130075D8CD7E0C14BFC54D6B09FD0856553ED9DCB29152A52089", {6, 5, 0, 1, 4, 2, 3}), 10: ("DC979EA061CD6E7E17F1062E1F359E1C15C902B06B47B2C4122AA2ED29B5A6B0", {6, 4, 0, 5, 2, 1, 3}), 6: ("2B4F4B2FF22C718FAD5E06C2F93CE4E727FD5FD0514CCF102FCE16036995339D", {2, 0, 3, 1, 6, 5, 4}), 5: ("21E9BAE456021A7BE5F4633345667BDDD7748F6DCA37842147560A8209BCECFE", {3, 4, 2, 6, 1, 0, 5})}
7
reason: all committed
done!
