process faults {5: ({0, 4}, 401488304)}
network faults {3: [{0}, {1}, {3, 5, 2, 6}, {4}], 2: [{2, 4, 5, 0}, {6, 1}, {3}]}
{5: ("927FE3E6A606D917FB24710EBB87B762A4454D5D41920AC9FB2BF09BC21A6565", {3, 6, 0, 5, 4, 2, 1}), 6: ("290CC51D228877F18EBB38B0FEBA5E2E275974D5DB4E752D21A9361003B0E7DA", {1, 4, 0, 3, 5, 6, 2}), 9: ("235564AA193CF7C72198F275BCAFD1149A0B61BE4550385608E85B5A9AAE44C5", {2, 5, 0, 3, 1, 4, 6}), 8: ("53CAE015EB36A680B0970D0E44443A9D850C7E552031107F775DB056599CEC2E", {6, 5, 1, 3, 4, 0, 2}), 10: ("E56D7F2AA659C2EECBFC27156A6C3A91AA285E54FF62AB09A22FBDB7208EA85C", {3, 1, 6, 5, 4, 2, 0}), 7: ("17897885FE6B845A56ACC4087CFB3B0AE46A2B815BDF85148BD5AC36DE92E405", {3, 1, 4, 2, 5, 0, 6})}
7
reason: all committed
done!
