process faults {6: ({4}, 3638239469)}
network faults {5: [{4, 0}, {1}, {2, 3}, {5, 6}], 6: [{4, 0}, {1, 2}, {5, 6, 3}]}
{9: ("C0EA8650705AC38D7243E3C087E145B95B725EE61A70D6630422F354C1270A70", {3, 0, 2, 4, 5, 6, 1}), 7: ("8B1BB90A21F1C0FAE4F0452BFF17489B748F2CC38671E876D4E057855328C525", {5, 0, 4, 6, 1, 2, 3}), 6: ("409BDC418D1D85E4E45B350713818008D16A092B1D798E13D77185F0B9FB8D5F", {4, 2, 5, 1, 6, 0, 3}), 10: ("F0AEB5459BD5840C7F3F296B6FCBDE7187F4D66023C2545F2C6BDD3BD01CCAF5", {3, 1, 2, 0, 6, 4, 5}), 5: ("A08E96CA5A1816C762C4E21147B3FA9AF2F5D9F264424BCC97C4DF74F6880B25", {4, 2, 5, 3, 0, 6, 1}), 8: ("63E92F857B1449A8DE246DE6351C731303EF5D936BCC52615FFEC1913E7714A6", {0, 2, 4, 5, 6, 3, 1})}
7
reason: all committed
done!
