process faults {7: ({4, 1, 2}, 321955909)}
network faults {}
{9: ("FD3B2843B6A24B9C582EBE4B7D2184B0DB06CE31459CE4FFB0E49473AB8B66F0", {1, 3, 0, 2, 5, 4, 6}), 6: ("E9AA4105094725E6F3AB3436023867F9DA0A354F641720BCB2B203B0B64170B4", {4, 1, 0, 2, 5, 6, 3}), 7: ("B2D8072FE7F426190040CADF5AB035A468B8C753AD05EEC55D8E1AF103DC844E", {5, 1, 6, 4, 0, 3, 2}), 8: ("E45A443A7E0A1A654908B107C710342375DB279640626DE2DB13F1B17465CC7C", {5, 2, 1, 3, 0, 6, 4}), 10: ("C2CF0F0D8AFC12D3E908A9FE2CC98201FC904692360E59678924CF5C3E3C3A05", {2, 5, 4, 1, 6, 0, 3}), 5: ("E3947FE0BA410C2095519E23FC6AC149D2DA2CBF986574D1BAF92B048F72C9B3", {5, 0, 1, 6, 4, 2, 3})}
7
reason: all committed
done!
