process faults {6: ({0, 4}, 1746755063)}
network faults {7: [{0}, {1, 4}, {2}, {3, 5, 6}]}
{5: ("9972AE7F519510BE218C98C2D10DCCAC6F28F569651970319A9F52B8EF1304A4", {6, 2, 0, 3, 5, 1, 4}), 9: ("BE0457FD33EB7D712E8A963C3D3942B615E5FCD41E14B1CF9D072566172C9BA5", {5, 3, 6, 4, 1, 0, 2}), 10: ("2459B90196E3F1F3E52D48E5B6B258F4C89F377CE3D25BDF6D6E324A82AD675D", {1, 2, 5, 3, 4, 6, 0}), 7: ("4DB0CDF2D325E483C67F59CF7462DEE8344F8FFFC5D5A6E8545A4FB58EF27817", {6, 2, 0, 3, 1, 4, 5}), 8: ("DAE26C3C76815883743695779F09E5FBC032015412FE6DFEA639910BD29FFD32", {5, 2, 0, 3, 6, 1, 4}), 6: ("98EBFA0C7650CA217A27C720B803143D2520F1D402F3E004DF6408D48B76B5C0", {3, 2, 1, 5, 6, 4, 0})}
7
reason: all committed
done!
